[tool.poetry]
name        = "crupydslparser"
version     = "0.0.0"
description = "Crupy DSL parser"
readme      = "README.md"
authors     = [
    "Yann MAGNIN <yann.magnin@ecole2600.com>",
]
packages    = [
    { include = "crupydslparser", from='CrupyDSLParser' },
]


[tool.poetry.scripts]
crupydsl    = 'crupydslparser.cli:crupydslparser_cli_entry'


[tool.poetry.dependencies]
python  = "3.11.*"
click   = "8.1.*"

[tool.poetry.dev-dependencies]
pynvim  = "0.5.*"
pylint  = "3.*"
mypy    = "1.*"
