[tool.poetry]
name        = "crupy"
version     = "0.0.0"
description = "Crupy language PoC"
readme      = "README.md"
authors     = [
    "Yann MAGNIN <yann.magnin@ecole2600.com>",
    "Yann MAJEROWICZ <yann.majerowicz@ecole2600.com>",
    "Joel RABAH <joel.rabah@ecole2600.com>",
]
packages    = [
    { include = "crupy", from='Crupy' },
]

[tool.poetry.dependencies]
python  = "3.11.*"
click   = "8.1.*"

[tool.poetry.dev-dependencies]
pynvim  = "0.5.*"
pylint  = "3.*"
mypy    = "1.*"
