name: 'Sanitize codebase'
on: [push]
jobs:
  sanitize-codebase:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout the codebase'
        uses: actions/checkout@v4
      - name: 'install CPython 3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 'install poetry'
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8'
      - name: 'Setup a local virtual environment'
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: 'define a cache for the virtual environment'
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: 'install the project dependencies'
        run: poetry install
      - name: 'check codebase'
        run: |
          poetry run pylint -d R0903,R0801 CrupyDSLParser/crupydslparser
          poetry run mypy --strict CrupyDSLParser/crupydslparser
          poetry run pyimportcheck CrupyDSLParser/crupydslparser
          poetry run pylint -d R0903,R0801 CrupyDSLParser/examples/crupycsv
          poetry run mypy --strict CrupyDSLParser/examples/crupycsv
          poetry run pyimportcheck CrupyDSLParser/crupydslparser
          poetry run pylint -d R0903,R0801 CrupyDSLParser/examples/crupyjson
          poetry run mypy --strict CrupyDSLParser/examples/crupyjson
          poetry run pyimportcheck CrupyDSLParser/crupydslparser
          poetry run pylint -d R0903,R0801 CrupyDSLParser/tests
          poetry run mypy --strict CrupyDSLParser/tests
      - name: 'check unittest'
        run: |
          poetry run crupycsv tests
          poetry run crupyjson tests
          poetry run pytest --tb=no
